In [5]:
import os
import pandas as pd

In [43]:
path = os.path.join(os.getenv("PROCESSED_DIR","./data/processed"), "tables", "labs.parquet")
df = pd.read_parquet(path)
df

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
0,MH59255,28.0,None,NaN,NaN,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
1,Date Collected: 03/18/2024,3.0,None,NaN,NaN,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
2,Iron Bind.Cap.(TIBC),261.0,None,250.0,450.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
3,UIBC 01,170.0,None,111.0,343.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
4,Iron 01,91.0,None,38.0,169.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
...,...,...,...,...,...,...,...,...,...,...,...
407,Protein - Total,6.4,g/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
408,Globulin - Total,2.2,g/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
409,MCHC,32.8,g/dL,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
410,Albumin,4.2,g/dL,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
411,Sex Hormone Binding Globulin - Male,25.0,nmol/L,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs

In [44]:
df[df['vendor'] == 'Ways2Well']

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
389,Basophils - %,1.1,%,NaN,NaN,None,2023-12-07,17,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
390,ALT,34.0,IU/L,NaN,NaN,None,2023-12-07,17,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
391,Testosterone Free - Male,261.1,pg/mL,NaN,NaN,None,2023-12-07,18,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
392,Hematocrit - Male,52.5,%,NaN,NaN,None,2023-12-07,18,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
393,Eosinophils - %,5.2,%,NaN,NaN,None,2023-12-07,18,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
394,T3 - Free,4.4,pg/mL,NaN,NaN,None,2023-12-07,18,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
395,Lymphocytes - %,35.2,%,NaN,NaN,None,2023-12-07,18,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
396,Creatinine,1.2,mg/dL,NaN,NaN,None,2023-12-07,19,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
397,AST,33.0,IU/L,NaN,NaN,None,2023-12-07,19,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
398,MCV,94.6,fL,NaN,NaN,None,2023-12-07,19,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
399,BUN,21.0,mg/dL,NaN,NaN,None,2023-12-07,19,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
400,Monocytes - %,9.6,%,NaN,NaN,None,2023-12-07,20,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
401,Glucose: Fasting,96.0,mg/dL,NaN,NaN,None,2023-12-07,20,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
402,MPV,9.2,fL,NaN,NaN,None,2023-12-07,20,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
403,Triglycerides,112.0,mg/dL,NaN,NaN,None,2023-12-07,20,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
404,DHEA-S - Male,343.0,g/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
405,HDL Cholesterol,51.0,mg/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
406,Neutrophils - %,48.9,%,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
407,Protein - Total,6.4,g/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
408,Globulin - Total,2.2,g/dL,NaN,NaN,None,2023-12-07,21,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
409,MCHC,32.8,g/dL,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
410,Albumin,4.2,g/dL,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs
411,Sex Hormone Binding Globulin - Male,25.0,nmol/L,NaN,NaN,None,2023-12-07,22,Ways2Well,data/labs/Ways2Well_20231207.pdf,labs

In [42]:
df[df['vendor'] == 'ways2well'].shape

(0, 11)

In [36]:
df[df['vendor'] == 'LabCorp']

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
0,MH59255,28.0,None,NaN,NaN,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
1,Date Collected: 03/18/2024,3.0,None,NaN,NaN,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
2,Iron Bind.Cap.(TIBC),261.0,None,250.0,450.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
3,UIBC 01,170.0,None,111.0,343.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
4,Iron 01,91.0,None,38.0,169.0,None,2024-03-18,1,LabCorp,data/labs/LabCorp_20240318.pdf,labs
...,...,...,...,...,...,...,...,...,...,...,...
384,"Triiodothyronine (T3), Free 01",3.1,None,2.0,4.4,None,2025-03-27,4,LabCorp,data/labs/LabCorp_20250327.pdf,labs
385,Apolipoprotein B 03,62.0,None,NaN,90.0,None,2025-03-27,4,LabCorp,data/labs/LabCorp_20250327.pdf,labs
386,425-417-3604,877.0,None,NaN,NaN,None,2025-03-27,4,LabCorp,data/labs/LabCorp_20250327.pdf,labs
387,05/26/1995,21025370.0,None,NaN,NaN,None,2025-03-27,4,LabCorp,data/labs/LabCorp_20250327.pdf,labs
388,Reference Interval,13.0,%,13.0,17.7,None,2025-03-27,5,LabCorp,data/labs/LabCorp_20250327.pdf,labs