In [13]:
import os
import pandas as pd

processed_dir = os.getenv("PROCESSED_DIR","./data/processed")

## Labs

In [14]:
path = os.path.join(processed_dir, "tables", "labs.parquet")
labs_df = pd.read_parquet(path)
labs_df

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
0,Iron Bind.Cap.(TIBC),261.00,ug/dL,250.00,450.00,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
1,UIBC,170.00,ug/dL,111.00,343.00,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
2,Iron,91.00,ug/dL,38.00,169.00,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
3,Iron Saturation,35.00,%,15.00,55.00,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
4,Ferritin,83.00,ng/mL,30.00,400.00,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
...,...,...,...,...,...,...,...,...,...,...,...
514,Neutrophils - Absolute,2.25,k/cumm,1.90,4.20,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
515,Lymphocytes - Absolute,1.62,k/cumm,1.44,2.54,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
516,Monocytes - Absolute,0.44,k/cumm,0.20,0.40,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
517,Eosinophils - Absolute,0.24,k/cumm,0.00,0.20,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
518,Basophils - Absolute,0.05,k/cumm,0.00,0.10,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs

In [15]:
labs_df[labs_df['vendor'] == 'Ways2Well']

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
329,Glucose - Fasting,81.00,mg/dL,75.00,86.00,None,2023-06-03,32,Ways2Well,data/raw/labs/Ways2Well_20230603.pdf,labs
330,Hemoglobin A1C,4.70,%,4.60,5.30,None,2023-06-03,32,Ways2Well,data/raw/labs/Ways2Well_20230603.pdf,labs
331,eAG,88.19,mg/dl,85.00,105.00,None,2023-06-03,32,Ways2Well,data/raw/labs/Ways2Well_20230603.pdf,labs
332,Insulin - Fasting,3.20,ÂµIU/ml,2.00,5.00,None,2023-06-03,32,Ways2Well,data/raw/labs/Ways2Well_20230603.pdf,labs
333,Triglyceride-Glucose Index (TyG),4.20,Index,0.00,4.40,None,2023-06-03,32,Ways2Well,data/raw/labs/Ways2Well_20230603.pdf,labs
...,...,...,...,...,...,...,...,...,...,...,...
514,Neutrophils - Absolute,2.25,k/cumm,1.90,4.20,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
515,Lymphocytes - Absolute,1.62,k/cumm,1.44,2.54,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
516,Monocytes - Absolute,0.44,k/cumm,0.20,0.40,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
517,Eosinophils - Absolute,0.24,k/cumm,0.00,0.20,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs
518,Basophils - Absolute,0.05,k/cumm,0.00,0.10,None,2023-12-07,12,Ways2Well,data/raw/labs/Ways2Well_20231207.pdf,labs

In [16]:
labs_df[labs_df['vendor'] == 'LabCorp']

,analyte,value,unit,ref_low,ref_high,flag,date,page,vendor,source,source_type
0,Iron Bind.Cap.(TIBC),261.00,ug/dL,250.0,450.0,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
1,UIBC,170.00,ug/dL,111.0,343.0,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
2,Iron,91.00,ug/dL,38.0,169.0,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
3,Iron Saturation,35.00,%,15.0,55.0,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
4,Ferritin,83.00,ng/mL,30.0,400.0,None,2024-03-18,1,LabCorp,data/raw/labs/LabCorp_20240318.pdf,labs
...,...,...,...,...,...,...,...,...,...,...,...
324,"C-Reactive Protein, Cardiac",1.34,mg/L,0.0,3.0,None,2025-03-27,3,LabCorp,data/raw/labs/LabCorp_20250327.pdf,labs
325,"Estradiol, Sensitive A",46.10,pg/mL,8.0,35.0,High,2025-03-27,3,LabCorp,data/raw/labs/LabCorp_20250327.pdf,labs
326,Insulin,4.30,uIU/mL,2.6,24.9,None,2025-03-27,4,LabCorp,data/raw/labs/LabCorp_20250327.pdf,labs
327,"Triiodothyronine (T3), Free",3.10,pg/mL,2.0,4.4,None,2025-03-27,4,LabCorp,data/raw/labs/LabCorp_20250327.pdf,labs
328,Apolipoprotein B,62.00,mg/dL,NaN,90.0,None,2025-03-27,4,LabCorp,data/raw/labs/LabCorp_20250327.pdf,labs

In [17]:
labs_df['vendor'].value_counts()

vendor
LabCorp      329
Ways2Well    190
Name: count, dtype: int64

In [23]:
labs_corpus_df = pd.read_parquet(os.path.join(processed_dir, "corpus", "labs_corpus.parquet"))
labs_corpus_df

,text,source,page,source_type,ingested_at
0,"Anderton, Tyler\nDOB: 05/26/1995\nPatient Repo...",data/raw/labs/LabCorp_20240318.pdf,1,labs,2025-09-07T15:43:39+00:00Z
1,"Anderton, Tyler\nDOB: 05/26/1995\nPatient Repo...",data/raw/labs/LabCorp_20240318.pdf,2,labs,2025-09-07T15:43:39+00:00Z
2,"Anderton, Tyler\nDOB: 05/26/1995\nPatient Repo...",data/raw/labs/LabCorp_20240318.pdf,3,labs,2025-09-07T15:43:39+00:00Z
3,"Anderton, Tyler\nDOB: 05/26/1995\nPatient Repo...",data/raw/labs/LabCorp_20240318.pdf,4,labs,2025-09-07T15:43:39+00:00Z
4,"Anderton, Tyler\nDOB: 05/26/1995\nPatient Repo...",data/raw/labs/LabCorp_20240318.pdf,5,labs,2025-09-07T15:43:39+00:00Z
...,...,...,...,...,...
166,Functional Health Report | Tyler Andert...,data/raw/labs/Ways2Well_20231207.pdf,25,labs,2025-09-07T15:43:40+00:00Z
167,Functional Health Report | Tyler Andert...,data/raw/labs/Ways2Well_20231207.pdf,26,labs,2025-09-07T15:43:40+00:00Z
168,Functional Health Report | Tyler Andert...,data/raw/labs/Ways2Well_20231207.pdf,27,labs,2025-09-07T15:43:40+00:00Z
169,Text box. Column header. Column 0 Row 0. PATIE...,data/raw/labs/lets_get_checked_20230417.pdf,1,labs,2025-09-07T15:43:40+00:00Z
170,Text box. Column header. Column 0 Row 0. Text ...,data/raw/labs/lets_get_checked_20230417.pdf,2,labs,2025-09-07T15:43:40+00:00Z

## Meds

In [18]:
path = os.path.join(processed_dir, "tables", "meds.parquet")
meds_df = pd.read_parquet(path)
meds_df

,medication,dose,dose_unit,dose_frequency,dose_frequency_unit,date_start,date_updated,date_stop,current,__source_file
0,LMNT,1,packet,4,daily,2023-01-01,2025-07-01,NaT,False,data/raw/medications/medications_20250831.xlsx
1,Cetirizine HCl,10,mg,1,daily,2023-01-01,NaT,2024-06-01,False,data/raw/medications/medications_20250831.xlsx
2,Finasteride,1,mg,1,daily,2018-01-01,NaT,2024-01-01,False,data/raw/medications/medications_20250831.xlsx
3,DHEA,10,mg,1,daily,2023-07-01,2023-10-01,NaT,False,data/raw/medications/medications_20250831.xlsx
4,Enclomiphene,25,mg,1,daily,2023-07-01,NaT,2023-09-30,False,data/raw/medications/medications_20250831.xlsx
5,Milk Thistle,140,mg,1,daily,2023-07-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
6,NAC,500,mg,1,daily,2023-07-01,NaT,2024-01-31,False,data/raw/medications/medications_20250831.xlsx
7,Omega-3,500,mg,1,daily,2018-01-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
8,Vitamin D,125,mcg,1,daily,2018-01-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
9,Multivitamin,1,pill,1,daily,2018-01-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
10,Creatine Monohydrate,5,g,1,daily,2018-01-01,2025-04-01,NaT,False,data/raw/medications/medications_20250831.xlsx
11,Caffeine,200,mg,1,daily,2020-01-01,NaT,2024-12-02,False,data/raw/medications/medications_20250831.xlsx
12,Tri-Magnesium,300,mg,1,daily,2023-07-01,NaT,2024-05-31,False,data/raw/medications/medications_20250831.xlsx
13,Ashwaganda,500,mg,1,daily,2022-10-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
14,BPC-157,500,mcg,1,daily,2023-07-01,2023-11-01,2024-09-30,False,data/raw/medications/medications_20250831.xlsx
15,Testosterone Cypionate,22,mg,1,daily,2023-10-01,2023-11-01,NaT,False,data/raw/medications/medications_20250831.xlsx
16,DHEA,25,mg,1,daily,2023-10-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
17,Testosterone Cypionate,26,mg,1,daily,2023-11-01,2023-12-01,NaT,False,data/raw/medications/medications_20250831.xlsx
18,Testosterone Cypionate,28,mg,1,daily,2023-12-01,2024-01-01,NaT,False,data/raw/medications/medications_20250831.xlsx
19,Testosterone Cypionate,30,mg,1,daily,2024-01-01,2024-02-01,NaT,False,data/raw/medications/medications_20250831.xlsx
20,Testosterone Cypionate,32,mg,1,daily,2024-02-01,2024-03-15,NaT,False,data/raw/medications/medications_20250831.xlsx
21,Fluticasone,100,mcg,1,daily,2024-03-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
22,Natural Desiccated Thyroid,60,mg,1,daily,2024-05-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
23,Tadalafil,6,mg,1,daily,2024-05-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
24,HCG,200,IU,3,weekly,2024-05-01,2025-05-25,NaT,False,data/raw/medications/medications_20250831.xlsx
25,Thyroid Support Complex,2,capsule,1,daily,2024-05-01,NaT,2025-07-31,False,data/raw/medications/medications_20250831.xlsx
26,Testosterone Cypionate,30,mg,1,daily,2024-03-15,2024-04-15,NaT,False,data/raw/medications/medications_20250831.xlsx
27,Testosterone Cypionate,28,mg,1,daily,2024-04-15,2024-05-01,NaT,False,data/raw/medications/medications_20250831.xlsx
28,Testosterone Cypionate,25,mg,1,daily,2024-05-01,2024-08-15,NaT,False,data/raw/medications/medications_20250831.xlsx
29,Magnesium Glycinate,240,mg,1,daily,2024-06-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
30,Testosterone Cypionate,22,mg,1,daily,2024-08-15,2024-10-21,NaT,False,data/raw/medications/medications_20250831.xlsx
31,Testosterone Cypionate,28,mg,1,daily,2024-10-21,2025-04-15,NaT,False,data/raw/medications/medications_20250831.xlsx
32,CBD,200,mg,1,daily,2024-06-01,NaT,2025-07-31,False,data/raw/medications/medications_20250831.xlsx
33,Tesamorelin,500,mcg,1,daily,2024-10-24,NaT,2025-01-31,False,data/raw/medications/medications_20250831.xlsx
34,Sermorelin,500,mcg,1,daily,2025-02-01,NaT,2025-05-09,False,data/raw/medications/medications_20250831.xlsx
35,Trazodone,25,mg,1,daily,2024-12-02,2025-02-01,NaT,False,data/raw/medications/medications_20250831.xlsx
36,Modafinil,50,mg,1,daily,2025-02-24,2025-05-01,NaT,False,data/raw/medications/medications_20250831.xlsx
37,Trazodone,50,mg,1,daily,2025-02-01,2025-03-01,NaT,False,data/raw/medications/medications_20250831.xlsx
38,Trazodone,75,mg,1,daily,2025-03-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
39,Xyzal,5,mg,1,daily,2025-04-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
40,Azelastine,274,mcg,1,daily,2025-04-01,NaT,2025-07-31,False,data/raw/medications/medications_20250831.xlsx
41,Finsateride Topical Foam,1,application,1,daily,2025-04-18,NaT,2025-08-06,False,data/raw/medications/medications_20250831.xlsx
42,HCG,200,IU,1,daily,2025-05-25,2025-07-06,NaT,False,data/raw/medications/medications_20250831.xlsx
43,HCG,300,IU,1,daily,2025-07-06,NaT,2025-07-31,False,data/raw/medications/medications_20250831.xlsx
44,Testosterone Cypionate,26,mg,3,weekly,2025-04-15,NaT,2025-06-06,False,data/raw/medications/medications_20250831.xlsx
45,Enclomiphene,25,mg,1,daily,2025-06-01,NaT,2025-08-16,False,data/raw/medications/medications_20250831.xlsx
46,Modafinil,100,mg,1,daily,2025-05-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
47,Relora,250,mg,2,daily,2025-07-08,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
48,LMNT,1,packet,2,daily,2025-07-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx
49,Creatine Monohydrate,10,g,1,daily,2025-04-01,NaT,NaT,True,data/raw/medications/medications_20250831.xlsx

In [22]:
meds_corpus_df = pd.read_parquet(os.path.join(processed_dir, "corpus", "meds_corpus.parquet"))
meds_corpus_df

,text,source,source_type,ingested_at
0,Medication: LMNT; Dose: 1 packet; Frequency: 4...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
1,Medication: Cetirizine HCl; Dose: 10 mg; Frequ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
2,Medication: Finasteride; Dose: 1 mg; Frequency...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
3,Medication: DHEA; Dose: 10 mg; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
4,Medication: Enclomiphene; Dose: 25 mg; Frequen...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
5,Medication: Milk Thistle; Dose: 140 mg; Freque...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
6,Medication: NAC; Dose: 500 mg; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
7,Medication: Omega-3; Dose: 500 mg; Frequency: ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
8,Medication: Vitamin D; Dose: 125 mcg; Frequenc...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
9,Medication: Multivitamin; Dose: 1 pill; Freque...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
10,Medication: Creatine Monohydrate; Dose: 5 g; F...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
11,Medication: Caffeine; Dose: 200 mg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
12,Medication: Tri-Magnesium; Dose: 300 mg; Frequ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
13,Medication: Ashwaganda; Dose: 500 mg; Frequenc...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
14,Medication: BPC-157; Dose: 500 mcg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
15,Medication: Testosterone Cypionate; Dose: 22 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
16,Medication: DHEA; Dose: 25 mg; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
17,Medication: Testosterone Cypionate; Dose: 26 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
18,Medication: Testosterone Cypionate; Dose: 28 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
19,Medication: Testosterone Cypionate; Dose: 30 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
20,Medication: Testosterone Cypionate; Dose: 32 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
21,Medication: Fluticasone; Dose: 100 mcg; Freque...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
22,Medication: Natural Desiccated Thyroid; Dose: ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
23,Medication: Tadalafil; Dose: 6 mg; Frequency: ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
24,Medication: HCG; Dose: 200 IU; Frequency: 3 we...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
25,Medication: Thyroid Support Complex; Dose: 2 c...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
26,Medication: Testosterone Cypionate; Dose: 30 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
27,Medication: Testosterone Cypionate; Dose: 28 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
28,Medication: Testosterone Cypionate; Dose: 25 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
29,Medication: Magnesium Glycinate; Dose: 240 mg;...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
30,Medication: Testosterone Cypionate; Dose: 22 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
31,Medication: Testosterone Cypionate; Dose: 28 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
32,Medication: CBD; Dose: 200 mg; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
33,Medication: Tesamorelin; Dose: 500 mcg; Freque...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
34,Medication: Sermorelin; Dose: 500 mcg; Frequen...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
35,Medication: Trazodone; Dose: 25 mg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
36,Medication: Modafinil; Dose: 50 mg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
37,Medication: Trazodone; Dose: 50 mg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
38,Medication: Trazodone; Dose: 75 mg; Frequency:...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
39,Medication: Xyzal; Dose: 5 mg; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
40,Medication: Azelastine; Dose: 274 mcg; Frequen...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
41,Medication: Finsateride Topical Foam; Dose: 1 ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
42,Medication: HCG; Dose: 200 IU; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
43,Medication: HCG; Dose: 300 IU; Frequency: 1 da...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
44,Medication: Testosterone Cypionate; Dose: 26 m...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
45,Medication: Enclomiphene; Dose: 25 mg; Frequen...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
46,Medication: Modafinil; Dose: 100 mg; Frequency...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
47,Medication: Relora; Dose: 250 mg; Frequency: 2...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
48,Medication: LMNT; Dose: 1 packet; Frequency: 2...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z
49,Medication: Creatine Monohydrate; Dose: 10 g; ...,data/raw/medications/medications_20250831.xlsx,meds,2025-09-07T15:43:44+00:00Z

## Whoop

In [19]:
whoop_dir = os.path.join(processed_dir, "tables")
whoop_journal_entries_df = pd.read_parquet(os.path.join(whoop_dir, "whoop_journal_entries.parquet"))
whoop_journal_entries_df

,Cycle start time,Cycle end time,Cycle timezone,Question text,Answered yes,Notes
0,2025-08-30 00:18:09,None,UTC-05:00,Listened to noise while asleep?,True,None
1,2025-08-30 00:18:09,None,UTC-05:00,Took prescription sleep medication?,True,None
2,2025-08-30 00:18:09,None,UTC-05:00,Engaged in sexual activity?,False,None
3,2025-08-30 00:18:09,None,UTC-05:00,Slept in the same bed as usual?,True,None
4,2025-08-30 00:18:09,None,UTC-05:00,Used marijuana?,False,None
...,...,...,...,...,...,...
21638,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,Used CBD oil in any form?,False,None
21639,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,Felt recovered?,True,None
21640,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,Ate food close to bedtime?,True,None
21641,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,Saw direct sunlight upon waking up?,True,None
21642,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,Took prescription sleep medication?,True,None

In [10]:
whoop_physiological_cycles_df = pd.read_parquet(os.path.join(whoop_dir, "whoop_physiological_cycles.parquet"))
whoop_physiological_cycles_df

,Cycle start time,Cycle end time,Cycle timezone,Recovery score %,Resting heart rate (bpm),Heart rate variability (ms),Skin temp (celsius),Blood oxygen %,Day Strain,Energy burned (cal),...,Asleep duration (min),In bed duration (min),Light sleep duration (min),Deep (SWS) duration (min),REM duration (min),Awake duration (min),Sleep need (min),Sleep debt (min),Sleep efficiency %,Sleep consistency %
0,2025-08-30 00:18:09,None,UTC-05:00,44.0,54.0,62.0,34.30,97.26,NaN,NaN,...,432.0,460.0,211.0,119.0,102.0,28.0,518.0,18.0,93.0,83.0
1,2025-08-28 23:43:00,2025-08-30 00:18:09,UTC-05:00,37.0,54.0,61.0,34.60,96.35,15.6,3124.0,...,469.0,495.0,221.0,151.0,97.0,26.0,498.0,0.0,94.0,85.0
2,2025-08-27 22:54:27,2025-08-28 23:43:00,UTC-05:00,72.0,52.0,72.0,34.10,96.25,15.5,3051.0,...,521.0,546.0,236.0,154.0,131.0,25.0,472.0,4.0,95.0,76.0
3,2025-08-26 23:26:30,2025-08-27 22:54:27,UTC-05:00,65.0,50.0,70.0,34.09,97.22,12.6,2361.0,...,498.0,533.0,231.0,140.0,127.0,35.0,505.0,0.0,93.0,78.0
4,2025-08-25 22:14:15,2025-08-26 23:26:30,UTC-05:00,57.0,52.0,70.0,33.90,96.19,16.4,3331.0,...,548.0,575.0,237.0,169.0,142.0,27.0,501.0,11.0,95.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,2022-09-17 22:36:20,2022-09-18 22:20:02,UTC-05:00,65.0,52.0,85.0,32.69,96.91,10.3,2104.0,...,448.0,520.0,267.0,102.0,79.0,72.0,526.0,23.0,86.0,84.0
1078,2022-09-16 21:53:01,2022-09-17 22:36:20,UTC-05:00,78.0,60.0,102.0,32.35,96.40,15.5,2711.0,...,495.0,520.0,357.0,31.0,107.0,25.0,537.0,27.0,95.0,NaN
1079,2022-09-15 22:58:46,2022-09-16 21:53:01,UTC-05:00,97.0,52.0,132.0,33.18,95.87,16.5,2584.0,...,411.0,497.0,244.0,73.0,94.0,86.0,468.0,2.0,82.0,NaN
1080,2022-09-14 21:52:24,2022-09-15 22:58:46,UTC-05:00,68.0,62.0,75.0,32.73,97.36,5.6,1938.0,...,529.0,640.0,362.0,72.0,95.0,111.0,533.0,0.0,84.0,NaN
1081,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,NaN,NaN,NaN,NaN,NaN,14.6,1412.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
whoop_sleeps_df = pd.read_parquet(os.path.join(whoop_dir, "whoop_sleeps.parquet"))
whoop_sleeps_df

,Cycle start time,Cycle end time,Cycle timezone,Sleep onset,Wake onset,Sleep performance %,Respiratory rate (rpm),Asleep duration (min),In bed duration (min),Light sleep duration (min),Deep (SWS) duration (min),REM duration (min),Awake duration (min),Sleep need (min),Sleep debt (min),Sleep efficiency %,Sleep consistency %,Nap
0,2025-08-30 00:18:09,None,UTC-05:00,2025-08-30 00:18:09,2025-08-30 08:03:26,85.0,14.4,432.0,460.0,211.0,119.0,102.0,28.0,518.0,18.0,93.0,83.0,False
1,2025-08-28 23:43:00,2025-08-30 00:18:09,UTC-05:00,2025-08-28 23:43:00,2025-08-29 08:21:22,87.0,14.7,469.0,495.0,221.0,151.0,97.0,26.0,498.0,0.0,94.0,85.0,False
2,2025-08-27 22:54:27,2025-08-28 23:43:00,UTC-05:00,2025-08-27 22:54:27,2025-08-28 08:02:53,89.0,14.4,521.0,546.0,236.0,154.0,131.0,25.0,472.0,4.0,95.0,76.0,False
3,2025-08-26 23:26:30,2025-08-27 22:54:27,UTC-05:00,2025-08-27 15:50:00,2025-08-27 16:20:00,5.0,14.7,13.0,30.0,11.0,2.0,0.0,17.0,467.0,4.0,48.0,NaN,True
4,2025-08-26 23:26:30,2025-08-27 22:54:27,UTC-05:00,2025-08-26 23:26:30,2025-08-27 08:21:29,90.0,13.9,498.0,533.0,231.0,140.0,127.0,35.0,505.0,0.0,93.0,78.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,2022-09-18 22:20:02,2022-09-19 22:41:43,UTC-05:00,2022-09-18 22:20:02,2022-09-19 07:31:20,95.0,14.0,482.0,549.0,182.0,139.0,161.0,67.0,510.0,34.0,88.0,87.0,False
1099,2022-09-17 22:36:20,2022-09-18 22:20:02,UTC-05:00,2022-09-17 22:36:20,2022-09-18 07:19:46,85.0,13.8,448.0,520.0,267.0,102.0,79.0,72.0,526.0,23.0,86.0,84.0,False
1100,2022-09-16 21:53:01,2022-09-17 22:36:20,UTC-05:00,2022-09-16 21:53:01,2022-09-17 06:33:34,92.0,14.0,495.0,520.0,357.0,31.0,107.0,25.0,537.0,27.0,95.0,NaN,False
1101,2022-09-15 22:58:46,2022-09-16 21:53:01,UTC-05:00,2022-09-15 22:58:46,2022-09-16 07:16:44,88.0,13.6,411.0,497.0,244.0,73.0,94.0,86.0,468.0,2.0,82.0,NaN,False
1102,2022-09-14 21:52:24,2022-09-15 22:58:46,UTC-05:00,2022-09-14 21:52:24,2022-09-15 08:32:29,99.0,13.7,529.0,640.0,362.0,72.0,95.0,111.0,533.0,0.0,84.0,NaN,False

In [12]:
whoop_workouts_df = pd.read_parquet(os.path.join(whoop_dir, "whoop_workouts.parquet"))
whoop_workouts_df

,Cycle start time,Cycle end time,Cycle timezone,Workout start time,Workout end time,Duration (min),Activity name,Activity Strain,Energy burned (cal),Max HR (bpm),Average HR (bpm),HR Zone 1 %,HR Zone 2 %,HR Zone 3 %,HR Zone 4 %,HR Zone 5 %,GPS enabled,Distance (meters),Altitude gain (meters),Altitude change (meters)
0,2025-08-27 22:54:27,2025-08-28 23:43:00,UTC-05:00,2025-08-28 10:40:08,2025-08-28 11:00:32,20,Assault Bike,5.9,145.0,149,121,76,19,0,0,0,False,NaN,NaN,NaN
1,2025-08-25 22:14:15,2025-08-26 23:26:30,UTC-05:00,2025-08-26 10:20:59,2025-08-26 10:41:21,20,Assault Bike,6.5,175.0,149,128,59,36,0,0,0,False,NaN,NaN,NaN
2,2025-08-21 22:36:17,2025-08-23 01:17:58,UTC-05:00,2025-08-22 09:41:01,2025-08-22 11:02:13,81,Weightlifting,7.5,306.0,145,103,51,1,0,0,0,False,NaN,NaN,NaN
3,2025-08-18 23:30:43,2025-08-19 22:46:32,UTC-05:00,2025-08-19 10:55:44,2025-08-19 12:26:18,90,Weightlifting,7.9,356.0,149,104,58,1,0,0,0,False,NaN,NaN,NaN
4,2025-08-17 00:30:15,2025-08-17 23:04:14,UTC-05:00,2025-08-17 07:33:00,2025-08-17 09:58:29,145,Motocross,14.6,1239.0,163,128,63,36,1,0,0,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,2022-09-18 22:20:02,2022-09-19 22:41:43,UTC-05:00,2022-09-19 17:25:36,2022-09-19 18:43:21,77,Box Fitness,15.7,884.0,175,144,0,15,33,49,3,False,NaN,NaN,NaN
715,2022-09-16 21:53:01,2022-09-17 22:36:20,UTC-05:00,2022-09-17 10:40:25,2022-09-17 11:17:11,36,Powerlifting,7.4,247.0,153,122,8,70,20,2,0,False,NaN,NaN,NaN
716,2022-09-16 21:53:01,2022-09-17 22:36:20,UTC-05:00,2022-09-17 09:27:55,2022-09-17 10:29:45,61,Box Fitness,13.5,556.0,179,133,8,44,19,19,10,False,NaN,NaN,NaN
717,2022-09-15 22:58:46,2022-09-16 21:53:01,UTC-05:00,2022-09-16 16:33:25,2022-09-16 17:40:16,66,Box Fitness,15.9,779.0,180,147,2,14,24,35,25,False,NaN,NaN,NaN
718,2022-09-14 00:00:00,2022-09-14 21:52:24,UTC-05:00,2022-09-14 17:22:28,2022-09-14 18:48:51,86,Box Fitness,13.5,723.0,174,130,8,41,30,19,2,False,NaN,NaN,NaN

In [20]:
whoop_corpus_df = pd.read_parquet(os.path.join(processed_dir, "corpus", "whoop_corpus.parquet"))
whoop_corpus_df

,text,source,source_type,ingested_at
0,WHOOP file workouts.csv with 719 rows; columns...,data/raw/whoop/my_whoop_data_2025_08_30/workou...,whoop,2025-09-07T15:43:50+00:00Z
1,WHOOP file sleeps.csv with 1103 rows; columns:...,data/raw/whoop/my_whoop_data_2025_08_30/sleeps...,whoop,2025-09-07T15:43:50+00:00Z
2,WHOOP file journal_entries.csv with 21643 rows...,data/raw/whoop/my_whoop_data_2025_08_30/journa...,whoop,2025-09-07T15:43:50+00:00Z
3,WHOOP file physiological_cycles.csv with 1082 ...,data/raw/whoop/my_whoop_data_2025_08_30/physio...,whoop,2025-09-07T15:43:50+00:00Z

In [24]:
whoop_corpus_df['text'][0]

'WHOOP file workouts.csv with 719 rows; columns: Cycle start time, Cycle end time, Cycle timezone, Workout start time, Workout end time, Duration (min), Activity name, Activity Strain, Energy burned (cal), Max HR (bpm)'